influx: http://198.18.128.15:8086
influx_bucket: stealthwatch
influx_org: helena-gg
influx_token: TYb6oixvMk0wx40f8cbAZoRB-mD87j55QYHSxduBih8s9QmM6eCOhpD9dHfZvGlPeXw5ugD-7IBWafzXNrI5pQ==
smc: 198.18.128.41
smc_pass: P@ssw9rd
smc_tenant_id: 301
smc_token: 510af979-3313-463c-ad35-20060491a3ad
smc_user: api
